// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogugseohzdiuztqknndm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndWdzZW9oemRpdXp0cWtubmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4ODcwODksImV4cCI6MjA1NTQ2MzA4OX0.F5Tv0ktJZqamMVM8t5-FYFb6LuubraeNej-I72_mu5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);